version: "3.9"

services:
  app:
    build: .
    container_name: spam-classifier-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000 
    networks:
      - monitoring

  dataset-runner:
    build: .
    container_name: dataset-runner
    depends_on:
      - app
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - API_URL=http://app:8000/api/classify
      - PYTHONUNBUFFERED=1
    volumes:
      - mlflow_data:/mlflow
    command: >
      sh -c "echo '⏳ Attente de 15s...' && 
             sleep 15 && 
             python api/src/dataset/dataset.py"
    networks:
      - monitoring

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow/mlflow.db 
      --default-artifact-root /mlflow/artifacts 
      --host 0.0.0.0 
      --port 5000
    volumes:
      - mlflow_data:/mlflow
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  mlflow_data: